### ISSUE TITLE
Does caption work?

### ISSUE THREAD

**Issue by mrspeaker** [watzak/react-native-instagram-share#1]
Hey, I just did something very similar to this, but noticed that the caption didn't appear in the instagram app. I assumed it was "by design": http://developers.instagram.com/post/125972775561/removing-pre-filled-captions-from-mobile-sharing

Is that incorrect? Does the caption actually work? Thanks!

**Comment by watzak** [comment]
Hello @mrspeaker 

Just checked it out and tested! Your are right! Instagram does not support the caption functionality anymore :-1: Only at existing third party apps ...

Do u have already found a workaround for that? 

Thanx for your feedback in advance!
Cheers

**Comment by mrspeaker** [comment]
Nah, I think we're out of luck for this one: it's a business decision by Instagram, so the only way around it is reverse-engineering their own APIs (but then you'll probably get banned). Feel free to close this issue off anyway!

**Comment by watzak** [comment]
Ok thanks for your feedback! 
Hopefully Instagram rethinks their strategy and is going to reopen the possibility to make tags from third party apps ;)

I will close this issue for now ...
